# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Random blue bits

# Short description (goes below the title; it will also be used in the RSS feed)
description: My web log of random stuff.

# Your name, as you want it to appear underneath each post and in the footer
author: Maded Batara III

# Your email if you want it to be linked on the contact page
author_email: mnbatara3@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /blog/tag

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://blubits.github.io

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 5
paginate_path: "/blog/:num/"

# Syntax highlighter
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]